language: node_js
node_js:
  - "0.10"

before_install:
  - npm install -g grunt-cli karma
  - node_modules/.bin/bower install

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: "grunt"
